Repository dense-analysis/ale, pull requests merged in 2021-01, with the labels that each got.

#3470 Add nvim floating window support (replaces #3314)
  autoload/ale/cursor.vim
  autoload/ale/floating_preview.vim
  autoload/ale/hover.vim
  doc/ale.txt
  plugin/ale.vim
  test/command_callback/test_fecs_command_callback.vader
  test/test_floating_preview.vader
  test/test_hover.vader
Labels: enhancement

#3535 Revert "Improves fixer performance for large buffers"
  autoload/ale/util.vim
Labels: bug

#3234 Enable ktlint fixer for kotlin files.
  autoload/ale/fix/registry.vim
Labels: enhancement

#3485 Fix Julia Language Server Support
  ale_linters/julia/languageserver.vim
  test/command_callback/test_julia_languageserver_callbacks.vader
Labels: stale

#3509 Feature: Add support for named-pipe sockets for LSPs
  autoload/ale/socket.vim
  doc/ale.txt
  test/dumb_named_pipe_server.py
  test/test_socket_connections.vader
Labels: enhancement
